name: "Secret Scanning"

on: [push, pull_request]

jobs:
  scan-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: HEAD~1  # Compare with the last commit
